import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });
const nvaLinks = [
  { name: 'Login', href: '/login' },
  { name: 'Register', href: '/register' },
  { name: 'Forgot Password', href: '/forgot-password' },
]

export const metadata: Metadata = {
  title: "Create Next App Products",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>


        {/* <div className="container mx-auto px-4 py-8"> */}
        <div className="border-blue-400 py-2 px-1 m-2">
            <div className="flex flex-row gap-4 border border-red-500 py-4" >
          {nvaLinks.map((lin) => (
              <div className="w-full" key={lin.name}><Link href={lin.href}><strong> {lin.name}</strong></Link></div>
              ))}
            </div>
        </div>
        {/* // <div className="flex flex-row mx-auto px-4 py-0">
          //   <div className="w-1/3 py-4 border-yellow-300" key={lin.name}>
          //     <Link className=" text-gray-400" href={lin.href} key={lin.name} >
          //       {lin.name}
          //     </Link>
          //   </div>
          // </div> */}

        {children}
      </body>
    </html>
  );
}
