import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LinkedIn Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='min-b-screen flex flex-col'>
      {/* <body className={inter.className}> */}
      {/* Toaster  */}

      <header className="border-b sticky top-0 bg-white z-50">{/* Header  */}
        <Header/>
      </header>
      <div className="bg-[#f4f2ed] flex-1 w-full">
        {children}
      </div>
      </body>
    </html>
  );
}
