// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }
import Nav from '@components/Nav'
import '@styles/globals.css'

export const metadata = {
  title:"Promptopia",
  description:"Discover & Share AI Prompts",
}

const RootLayout = ({children,}: Readonly<{children:React.ReactNode}>) => {
  return (
    <html lang='en'>
      <body>
      <div className='main'>
        <div className='gradient' /> 
      </div>
      <main className='app'>
        <Nav/>
        {children}
      </main>
      </body>
    </html>
  )
}

export default RootLayout